### ISSUE TITLE
PI to pi; Pause to Play broken

### ISSUE THREAD

**Issue by gggustafson** [josancamon19/flutter_countdown_timer#3]
In TimerPainter, **PI** is depreciated and should be replaced with **pi**.

When the app has been started (Icons.play_arrow tapped) and then paused (Icons.pause tapped), the icon does not change back to Icons.play_arrow. As a matter of fact, the icon remains Icons.pause from the first time it is tapped.

Please advise the fix.

**Comment by gggustafson** [comment]
Here is the fix for the failure of the icon to change.

1. In the class **_HomeState**, add:

`  bool icon_changed;`

after the declaration of **AnimationController**.

2. In the override of **initState**, add:

`  icon_changed = false;`

3. Rewrite the onPressed event handler of the FloatingActionButton: 

```
onPressed: ( )
  {
  setState ( ( )
    {
    icon_changed = !icon_changed;

    if ( animationController.isAnimating )
      {
      animationController.stop ( );
      }
    else
      {
      animationController.reverse (
        from: ( animationController.value == 0.0 ) ?
                1.0 :
                animationController.value );
      }
    } );
  },

```
**icon_changed** becomes the state variable that will be tested when the FAB re-renders. This action will cause the FAB icon to be changed.

**Comment by josancamon19** [comment]
Hi @gggustafson thanks for taking the time to fix this issue and sorry for my late reply, your solution worked pretty well, I'll try to improve the project as soon as possible.

**Comment by gggustafson** [comment]
You're welcome.
